#!/bin/bash

# Make sure we are in the script directory
ScriptDIR=$(cd `dirname $0` && pwd)
if [ $ScriptDIR != $PWD ]; then
   echo "Ce script doit être executé depuis son dossier" 1>&2
   exit
fi

#On récupère le nombre de sessions actives de Yane
C=`sudo ./yane  -l | wc -l`

#On vérifie qu'aucune session n'est déjà lancée
if [ "$C" != "0" ] ; then
  echo "Une session est déjà lancée pour la fermer executez la commande:"
  echo "   STOP"
  exit

else
  #On copie les scripts dans le dossier partagé du Docker correspondant
  cp ./scripts/Routeur_Fai_Acces ./files/Routeur_Fai_Acces/etc/scripts/init
  cp ./scripts/Box ./files/Box/etc/scripts/init
  cp ./scripts/Routeur_Fai_Interconnexion ./files/Routeur_Fai_Interconnexion/etc/scripts/init
  cp ./scripts/Serveur_DNS ./files/Serveur_DNS/etc/scripts/init
  cp ./scripts/Routeur_Fai_Services ./files/Routeur_Fai_Services/etc/scripts/init
  cp ./scripts/Serveur_Web ./files/Serveur_Web/var/scripts/init
  cp ./scripts/Serveur_Ftp ./files/Serveur_Ftp/etc/scripts/init
  echo 'Chargement des VM..'
  #On lance Yane
  sudo ./yane > /dev/null
  exit
fi
