#!/bin/bash

ip addr add 192.168.148.254/25 dev eth0
ip link set dev eth0 up
ip addr add 200.6.252.1/26 dev eth1
ip link set dev eth1 up
echo 1 > /proc/sys/net/ipv4/ip_forward
# Partie routage Statique et dynamique.
ip route add 0.0.0.0/0 via 200.6.252.2
#ip route add 200.6.252.128/26 via 200.6.252.2
#ip route add 200.6.252.192/26 via 200.6.252.2


# Configuration DHCP
service isc-dhcp-server start
# translation d'adresse par le nat forwarding
iptables -t nat -A POSTROUTING -s 192.168.148.128/25 -j MASQUERADE
iptables --policy FORWARD DROP
iptables -P INPUT DROP 
iptables -A FORWARD -i eth0 -o eth1 -j ACCEPT
iptables -A INPUT -p udp --dport 67:68 -j ACCEPT
iptables -A FORWARD -p icmp --icmp-type echo-request -j ACCEPT
iptables -A INPUT -p icmp --icmp-type echo-reply -j ACCEPT
iptables -A INPUT -p udp  --dport 520 -j ACCEPT
iptables -A FORWARD -p all -i eth0 -j ACCEPT
iptables -A FORWARD -p icmp -i eth1 -j ACCEPT
iptables -A FORWARD -p tcp -i eth1 --sport 80 -j ACCEPT
iptables -A FORWARD -p tcp -i eth1 --dport 80 -j ACCEPT
iptables -A FORWARD -p udp -i eth1 --sport 53 -j ACCEPT
iptables -A FORWARD -p udp -i eth1 --dport 53 -j ACCEPT

iptables -A FORWARD -p tcp --sport 21 -j ACCEPT 
iptables -A FORWARD -p tcp --sport 20 -j ACCEPT
iptables -A FORWARD -p tcp --sport 1024 -j ACCEPT
