#!/bin/bash
# partie Routage Statique et dynamique.

#ip addr add 192.168.148.129/25 dev eth0
#ip link set dev eth0 up
#echo 1 > /proc/sys/net/ipv4/ip_forward
#ip route add 0.0.0.0/0 via 192.168.148.254 

# Partie Configuration DHCP 
dhclient eth0

