#!/bin/bash
ip addr add 200.6.252.130/26 dev eth0
ip link set dev eth0 up
ip addr add 200.6.252.254/26 dev eth1
ip link set dev eth1 up
echo 1 > /proc/sys/net/ipv4/ip_forward
#Partie Routage Statique
#ip route add 200.6.252.0/26 via 200.6.252.129
#ip route add 200.6.252.64/26 via 200.6.252.129
#ip route add 192.168.148.128/25 via 200.6.252.129

# Filtrage de tous de ce qui rentre  et tout ce qui est transmis
iptables --policy FORWARD DROP
iptables -P INPUT DROP
iptables -A FORWARD -p all -i eth0 -j ACCEPT
iptables -A FORWARD -p icmp -i eth1 -j ACCEPT
iptables -A FORWARD -p icmp --icmp-type echo-reply -j ACCEPT
iptables -A INPUT -p icmp --icmp-type echo-reply -j ACCEPT
iptables -A INPUT -p icmp --icmp-type echo-request -j ACCEPT
iptables -A FORWARD -p tcp -i eth1 --sport 80 -j ACCEPT
iptables -A FORWARD -p tcp -i eth1 --dport 80 -j ACCEPT
iptables -A FORWARD -p udp -i eth1 --sport 53 -j ACCEPT
iptables -A FORWARD -p udp -i eth1 --dport 53 -j ACCEPT
iptables -A INPUT -p udp --dport 520 -j ACCEPT

iptables -A FORWARD -p tcp --dport 21 -j ACCEPT
iptables -A FORWARD -p tcp --dport 20 -j ACCEPT
iptables -A FORWARD -p tcp --dport 1024: -j ACCEPT
