#!/bin/bash
ip addr add 200.6.252.195/26 dev eth0
ip link set dev eth0 up
echo 1 > /proc/sys/net/ipv4/ip_forward
ip route add 0.0.0.0/0 via 200.6.252.254 
# Dem
chmod 755 -R /home/ftpdownload
chmod -R 755 /etc/proftpd 
echo 200.6.252.195 Serveur_FTP > /etc/hosts
service proftpd start
adduser ftp nogroup
adduser user1 --shell /bin/false --home /home/user1
