#!/bin/bash
ip addr add 200.6.252.194/26 dev eth0
ip link set dev eth0 up
echo 1 > /proc/sys/net/ipv4/ip_forward
ip route add 0.0.0.0/0 via 200.6.252.254 
service apache2 start
chmod 711 /var/www/html
chmod 644 /var/www/html/index.html 
